language: go
go:
    - 1.7
notificaitons:
  email:
    recipients: dave@brophy.uk
    on_failure: always
install:
  - go get -u github.com/dave/kerr/kcov
  - go get -t -v ./...
script:
  - kcov -r github.com/dave/geny
after_success:
  - bash <(curl -s https://codecov.io/bash)
